#!/usr/bin/env bash
# Idempotent bootstrap for the Amealio replatforming workspace.
#
# The target repo (replateform-amealio) is intentionally empty; the runnable
# code lives in the sibling REFERENCE repositories that Cursor checks out next
# to it. This script installs the system databases those apps need and the
# node dependencies for each required app.
#
# Safe to run repeatedly. Required npm installs are fail-fast (non-zero exit).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_REPO="$(cd "$SCRIPT_DIR/.." && pwd)"
REPOS_ROOT="$(cd "$TARGET_REPO/.." && pwd)"
echo "==> Workspace root: $REPOS_ROOT"

# ---------------------------------------------------------------------------
# 1. System databases (PostgreSQL, Redis, MongoDB).
# ---------------------------------------------------------------------------
install_system_dbs() {
  local need_pg=0 need_redis=0 need_mongo=0
  command -v pg_ctlcluster >/dev/null 2>&1 || need_pg=1
  command -v redis-server  >/dev/null 2>&1 || need_redis=1
  command -v mongod        >/dev/null 2>&1 || need_mongo=1

  if [[ $need_pg -eq 0 && $need_redis -eq 0 && $need_mongo -eq 0 ]]; then
    echo "==> System databases already installed."
    return 0
  fi

  echo "==> Installing system databases (pg=$need_pg redis=$need_redis mongo=$need_mongo)"
  sudo apt-get update -y

  if [[ $need_pg -eq 1 || $need_redis -eq 1 ]]; then
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql postgresql-contrib redis-server
  fi

  if [[ $need_mongo -eq 1 ]]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    curl -fsSL https://pgp.mongodb.com/server-8.0.asc \
      | sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg --dearmor
    echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu ${VERSION_CODENAME}/mongodb-org/8.0 multiverse" \
      | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
    sudo apt-get update -y
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mongodb-org
  fi
}
install_system_dbs

# ---------------------------------------------------------------------------
# 2. Local-development-only .env stubs (create if missing; never overwrite).
#    Values are placeholders for Cloud Agent / local use only — not production.
# ---------------------------------------------------------------------------
NEST_DIR="$REPOS_ROOT/amealio-nestjs-backend"
FEATHERS_DIR="$REPOS_ROOT/Amealio-VendorDashboard"

if [[ -d "$NEST_DIR" && ! -f "$NEST_DIR/.env" ]]; then
  echo "==> Writing LOCAL-DEV-ONLY stub $NEST_DIR/.env (will not overwrite existing)"
  cat > "$NEST_DIR/.env" <<'EOF'
# LOCAL DEVELOPMENT ONLY — generated by .cursor/install.sh
# Do not use these values in production. This file is created only when missing.
PORT=3000
DB_HOST=127.0.0.1
DB_PORT=5432
DB_USER=postgres
DB_PASS=local-dev-only-not-for-prod
DB_NAME=delivery_tracking
JWT_SECRET=local-dev-only-jwt-secret-not-for-prod
EOF
fi

if [[ -d "$FEATHERS_DIR" && ! -f "$FEATHERS_DIR/.env" ]]; then
  echo "==> Writing LOCAL-DEV-ONLY stub $FEATHERS_DIR/.env (will not overwrite existing)"
  cat > "$FEATHERS_DIR/.env" <<'EOF'
# LOCAL DEVELOPMENT ONLY — generated by .cursor/install.sh
# Do not use these values in production. This file is created only when missing.
ENV=DEVELOPMENT
NODE_ENV=development
HOST=localhost
PORT=5001
API=api/v1
BASEURL=http://localhost:5001
MONGODB=mongodb://127.0.0.1:27017/amealio_dev
ONDC_MICRO_SERVER_URL=http://localhost:9999
PAGINATE_DEFAULT=10
PAGINATE_MAX=50
SHORTTOKENEXPIRY=5m
LONGTOKENEXPIRY=10080m
MOBILETOKENEXPIRY=43800m
UNREGISTEREDUSERTOKENEXPIRY=210m
AUTHENTICATION_ENTITY=User
AUTHENTICATION_SERVICE=user-service
AUTHENTICATION_ENTITYID=_id
AUTHENTICATION_SECRET=local-dev-only-secret-not-for-prod
AUTHENTICATION_AUTHSTRATEGIES=["jwt","local","phone","facebook"]
AUTHENTICATION_JWTOPTIONS_HEADER_TYP=access
AUTHENTICATION_JWTOPTIONS_AUDIENCE=http://localhost
AUTHENTICATION_JWTOPTIONS_ISSUER=feathers
AUTHENTICATION_JWTOPTIONS_ALGORITHM=HS256
AUTHENTICATION_JWTOPTIONS_EXPIRESIN=30d
AUTHENTICATION_LOCAL_USERNAMEFIELD=email
AUTHENTICATION_LOCAL_PASSWORDFIELD=password
AUTHENTICATION_PHONE_USERNAMEFIELD=mobile_number
AUTHENTICATION_PHONE_PASSWORDFIELD=password
AUTHENTICATION_OAUTH_REDIRECT=/
VENDORAUTHENTICATION_ENTITY=VendorUser
VENDORAUTHENTICATION_SERVICE=vendor-user
VENDORAUTHENTICATION_SECRET=local-dev-only-vendor-secret-not-for-prod
VENDORAUTHENTICATION_AUTHSTRATEGIES=["jwt","local","phone"]
VENDORAUTHENTICATION_JWTOPTIONS_HEADER_TYP=access
VENDORAUTHENTICATION_JWTOPTIONS_AUDIENCE=http://localhost
VENDORAUTHENTICATION_JWTOPTIONS_ISSUER=feathers
VENDORAUTHENTICATION_JWTOPTIONS_ALGORITHM=HS256
VENDORAUTHENTICATION_JWTOPTIONS_EXPIRESIN=30d
VENDORAUTHENTICATION_LOCAL_USERNAMEFIELD=email
VENDORAUTHENTICATION_LOCAL_PASSWORDFIELD=password
VENDORAUTHENTICATION_PHONE_USERNAMEFIELD=mobile_number
VENDORAUTHENTICATION_PHONE_PASSWORDFIELD=password
EOF
fi

# ---------------------------------------------------------------------------
# 3. Required Node dependency installs (fail-fast; npm install is idempotent).
# ---------------------------------------------------------------------------
npm_install_required() {
  local dir="$1"; shift
  if [[ ! -d "$dir" ]]; then
    echo "ERROR: required app directory missing: $dir" >&2
    return 1
  fi
  if [[ ! -f "$dir/package.json" ]]; then
    echo "ERROR: required package.json missing in: $dir" >&2
    return 1
  fi
  echo "==> npm install: $dir  ($*)"
  # --no-audit/--no-fund/--prefer-offline keep installs fast and network-resilient;
  # the audit/funding metadata calls otherwise dominate runtime on cached trees.
  ( cd "$dir" && npm install --no-audit --no-fund --prefer-offline "$@" )
}

npm_install_required "$REPOS_ROOT/amealio-nestjs-backend"
npm_install_required "$REPOS_ROOT/amealio-self-delivery-app"
npm_install_required "$REPOS_ROOT/amealio_web_app" --legacy-peer-deps
npm_install_required "$REPOS_ROOT/Amealio-VendorDashboard"

echo "==> install.sh complete."
