import type { OrderRecord } from '../domain/ordering.types';

export function serializeOrder(order: OrderRecord) {
  return {
    id: order.id,
    orderNumber: order.orderNumber,
    merchantId: order.merchantId,
    restaurantId: order.restaurantId,
    userId: order.userId,
    type: order.type,
    status: order.status,
    cancelReason: order.cancelReason,
    deliveryPersonId: order.deliveryPersonId,
    deliveryPerson: order.deliveryPerson ?? null,
    currencyCode: order.currencyCode,
    subtotalMinor: order.subtotalMinor.toString(),
    taxTotalMinor: order.taxTotalMinor.toString(),
    discountTotalMinor: order.discountTotalMinor.toString(),
    feeTotalMinor: order.feeTotalMinor.toString(),
    deliveryChargeMinor: order.deliveryChargeMinor.toString(),
    grandTotalMinor: order.grandTotalMinor.toString(),
    tipMinor: order.tipMinor.toString(),
    donationMinor: order.donationMinor.toString(),
    offerId: order.offerId,
    couponId: order.couponId,
    items: order.items.map((i) => ({
      id: i.id,
      menuItemId: i.menuItemId,
      nameSnapshot: i.nameSnapshot,
      variantSnapshot: i.variantSnapshot,
      quantity: i.quantity,
      unitPriceMinor: i.unitPriceMinor.toString(),
      lineTotalMinor: i.lineTotalMinor.toString(),
      currencyCode: i.currencyCode,
    })),
    statusEvents: order.statusEvents.map((e) => ({
      id: e.id,
      fromStatus: e.fromStatus,
      toStatus: e.toStatus,
      actorType: e.actorType,
      actorId: e.actorId,
      reason: e.reason,
      createdAt: e.createdAt,
    })),
    paymentIntents: order.paymentIntents.map((p) => ({
      id: p.id,
      status: p.status,
      method: p.method,
      amountMinor: p.amountMinor.toString(),
      currencyCode: p.currencyCode,
      razorpayOrderId: p.razorpayOrderId,
      createdAt: p.createdAt,
    })),
  };
}
